version: "3.7"
services:
  postgresql:
    build: ./PostgreSQL
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
      - "POSTGRES_DB=docker"
  test-app:
    build: ./microservices/test-app
    ports:
      - "8080:8080"
  # TODO
  # kafka-consumer:
  #   build: ./microservices/kafka-consumer
  #   ports:
  #     - "8080:8081"
  # kafka-producer:
  #   build: ./microservices/kafka-producer
  #   ports:
  #     - "8080:8082"
  # kafka:
  #   build: ./kafka
  # zookeeper:
  #   build: ./zookeeper
